spring:
  application:
    name: "LabWork63_EduFood"
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 9191

  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true
    #
    cache: false
    template-loader-path: classpath:/templates/
    prefer-file-system-access: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 200ms

logging:
  level:
    root: info
#    kg.attractor.job_search_java_25: DEBUG
    org.springframework.web: INFO
    org:
      springframework:
        security: debug
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level){blue} %clr([%X{requestId}]){magenta} %clr(%logger{36}){cyan} - %msg%n"
    file:
      path: logs